"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import {
  FileText,
  Map,
  GitBranch,
  Cpu,
  ClipboardList,
  BrainCircuit,
  Search,
  Layers,
} from "lucide-react";

const features = [
  {
    icon: BrainCircuit,
    title: "AI Research Engine",
    desc: "Deep-dive into market research, competitive analysis, and user personas — all generated by AI with a single prompt.",
    tag: "Research",
    gradient: "from-violet-500/15 to-purple-600/5",
    border: "border-violet-500/20",
    iconColor: "text-violet-400",
    iconBg: "bg-violet-500/10",
  },
  {
    icon: FileText,
    title: "PRD Generator",
    desc: "Transform rough ideas into complete, structured Product Requirements Documents that your whole team can act on.",
    tag: "Documents",
    gradient: "from-blue-500/15 to-cyan-600/5",
    border: "border-blue-500/20",
    iconColor: "text-blue-400",
    iconBg: "bg-blue-500/10",
  },
  {
    icon: Map,
    title: "Roadmap Builder",
    desc: "Visualize your product roadmap with AI-suggested milestones, timelines, and sprint breakdowns.",
    tag: "Planning",
    gradient: "from-emerald-500/15 to-teal-600/5",
    border: "border-emerald-500/20",
    iconColor: "text-emerald-400",
    iconBg: "bg-emerald-500/10",
  },
  {
    icon: GitBranch,
    title: "Architecture Diagrams",
    desc: "Generate production-ready system architecture diagrams in Mermaid.js with detailed component breakdowns.",
    tag: "Architecture",
    gradient: "from-amber-500/15 to-orange-600/5",
    border: "border-amber-500/20",
    iconColor: "text-amber-400",
    iconBg: "bg-amber-500/10",
  },
  {
    icon: ClipboardList,
    title: "Task Management",
    desc: "Break down your product into actionable tasks with priorities, owners, and status tracking built in.",
    tag: "Execution",
    gradient: "from-rose-500/15 to-red-600/5",
    border: "border-rose-500/20",
    iconColor: "text-rose-400",
    iconBg: "bg-rose-500/10",
  },
  {
    icon: Layers,
    title: "Unified Workspace",
    desc: "One place for your entire product lifecycle. From first idea to shipped feature — no context switching.",
    tag: "Workspace",
    gradient: "from-indigo-500/15 to-violet-600/5",
    border: "border-indigo-500/20",
    iconColor: "text-indigo-400",
    iconBg: "bg-indigo-500/10",
  },
];

function FeatureCard({ feature, index }: { feature: (typeof features)[0]; index: number }) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });
  const Icon = feature.icon;

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 50 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, delay: (index % 3) * 0.12, ease: [0.25, 0.46, 0.45, 0.94] }}
      whileHover={{ y: -6, scale: 1.015 }}
      className={`group relative overflow-hidden rounded-3xl border ${feature.border} bg-gradient-to-br ${feature.gradient} p-8 backdrop-blur-sm transition-all duration-300 hover:shadow-2xl`}
    >
      <div className={`mb-5 inline-flex rounded-xl ${feature.iconBg} p-3`}>
        <Icon className={`h-6 w-6 ${feature.iconColor}`} />
      </div>

      <div className="mb-2">
        <span className={`text-xs font-medium uppercase tracking-widest ${feature.iconColor} opacity-70`}>
          {feature.tag}
        </span>
      </div>

      <h3 className="mb-3 text-xl font-semibold text-white" style={{ fontFamily: "var(--font-sora)" }}>
        {feature.title}
      </h3>

      <p className="text-sm leading-relaxed text-zinc-400">{feature.desc}</p>

      {/* Corner shimmer on hover */}
      <div className="pointer-events-none absolute -right-16 -top-16 h-32 w-32 rounded-full bg-white/[0.03] transition-transform duration-500 group-hover:scale-150" />
    </motion.div>
  );
}

export default function Features() {
  const sectionRef = useRef(null);
  const titleInView = useInView(sectionRef, { once: true, margin: "-100px" });

  return (
    <section id="features" className="relative py-32">
      {/* Background */}
      <div className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
        <div className="absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
      </div>

      <div className="mx-auto max-w-7xl px-6">
        {/* Header */}
        <div ref={sectionRef} className="mb-20 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={titleInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5 }}
            className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-1.5 text-sm text-zinc-400"
          >
            Everything you need
          </motion.div>

          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            animate={titleInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="mx-auto max-w-2xl text-5xl font-bold text-white md:text-6xl"
            style={{ fontFamily: "var(--font-sora)" }}
          >
            The full stack for{" "}
            <span className="bg-gradient-to-r from-zinc-300 to-zinc-600 bg-clip-text text-transparent">
              product builders
            </span>
          </motion.h2>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={titleInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="mx-auto mt-6 max-w-xl text-lg text-zinc-400"
          >
            From ideation to deployment, BuilderOS provides every tool your team needs to ship faster and smarter.
          </motion.p>
        </div>

        {/* Grid */}
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, i) => (
            <FeatureCard key={feature.title} feature={feature} index={i} />
          ))}
        </div>
      </div>
    </section>
  );
}
